package subscriptionstatuses

const (
	// Trialing ...
	Trialing = "trialing"
	// Active ...
	Active = "active"
	// PastDue ...
	PastDue = "past_due"
	// Cancelled ...
	Cancelled = "canceled"
	// Unpaid ...
	Unpaid = "unpaid"
)
